/** @type {import('tailwindcss').Config} */
export default {
	content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
	darkMode: "class",
	theme: {
		extend: {
			colors: {
				"on-secondary-container": "#bfbfbf",
				"inverse-surface": "#faf8ff",
				"on-primary": "#3f4041",
				"surface": "#0a0e1a",
				"secondary-container": "#3a3c3c",
				"on-surface-variant": "#9daad4",
				"tertiary-fixed-dim": "#d0c7e8",
				"on-secondary": "#1f2021",
				"surface-container-lowest": "#000000",
				"primary-container": "#454747",
				"error": "#ee7d77",
				"on-error-container": "#ff9993",
				"on-tertiary-container": "#4f4964",
				"on-primary-fixed": "#3e4040",
				"secondary-dim": "#9d9e9e",
				"secondary": "#9d9e9e",
				"on-tertiary-fixed-variant": "#58526e",
				"primary": "#c6c6c7",
				"primary-fixed": "#e2e2e2",
				"on-primary-fixed-variant": "#5a5c5c",
				"tertiary": "#ece4ff",
				"inverse-on-surface": "#515463",
				"surface-variant": "#172447",
				"secondary-fixed-dim": "#d4d4d4",
				"background": "#0a0e1a",
				"error-dim": "#bb5551",
				"surface-container-low": "#0d1324",
				"error-container": "#7f2927",
				"secondary-fixed": "#e3e2e2",
				"on-error": "#490106",
				"surface-container-high": "#141e3b",
				"on-secondary-fixed": "#3e3f40",
				"on-primary-container": "#d0d0d0",
				"tertiary-dim": "#d0c7e8",
				"primary-dim": "#b8b9b9",
				"on-tertiary": "#57516d",
				"on-surface": "#dfe4ff",
				"surface-container": "#11192f",
				"tertiary-container": "#ded5f7",
				"surface-dim": "#0a0e1a",
				"primary-fixed-dim": "#d4d4d4",
				"outline": "#68749c",
				"inverse-primary": "#5e5f60",
				"surface-tint": "#c6c6c7",
				"on-background": "#dfe4ff",
				"tertiary-fixed": "#ded5f7",
				"surface-bright": "#1a2a54",
				"outline-variant": "#3a476c",
				"surface-container-highest": "#172447",
				"on-secondary-fixed-variant": "#5a5c5c",
				"on-tertiary-fixed": "#3c3650"
			},
			fontFamily: {
				"headline": ["Newsreader", "serif"],
				"body": ["Inter", "sans-serif"],
				"label": ["Inter", "sans-serif"]
			},
			borderRadius: {
				"DEFAULT": "0px",
				"lg": "0px",
				"xl": "0px",
				"full": "9999px"
			},
		},
	},
	plugins: [
		require('@tailwindcss/forms'),
		require('@tailwindcss/container-queries'),
	],
}
